package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private int codLaboratorio;
     private String nomLab;
     private String alias;
     private Set usuarios = new HashSet(0);
     private Set investigacions = new HashSet(0);

    public Laboratorio() {
    }

	
    public Laboratorio(int codLaboratorio, String nomLab) {
        this.codLaboratorio = codLaboratorio;
        this.nomLab = nomLab;
    }
    public Laboratorio(int codLaboratorio, String nomLab, String alias, Set usuarios, Set investigacions) {
       this.codLaboratorio = codLaboratorio;
       this.nomLab = nomLab;
       this.alias = alias;
       this.usuarios = usuarios;
       this.investigacions = investigacions;
    }
   
    public int getCodLaboratorio() {
        return this.codLaboratorio;
    }
    
    public void setCodLaboratorio(int codLaboratorio) {
        this.codLaboratorio = codLaboratorio;
    }
    public String getNomLab() {
        return this.nomLab;
    }
    
    public void setNomLab(String nomLab) {
        this.nomLab = nomLab;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getInvestigacions() {
        return this.investigacions;
    }
    
    public void setInvestigacions(Set investigacions) {
        this.investigacions = investigacions;
    }




}


