package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private int idLote;
     private BitacoraLab bitacoraLab;
     private Lote lote;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Integer estatus;
     private Set mantenimientos = new HashSet(0);
     private Set lotes = new HashSet(0);
     private Set muestras = new HashSet(0);
     
     private String nombreLote;

    public Lote() {
    }

	
    public Lote(int idLote, BitacoraLab bitacoraLab) {
        this.idLote = idLote;
        this.bitacoraLab = bitacoraLab;
    }
    public Lote(int idLote, BitacoraLab bitacoraLab, Lote lote, Date fechaCreacion, Date fechaModificacion, Integer estatus, Set mantenimientos, Set lotes, Set muestras,String nombreLote) {
       this.idLote = idLote;
       this.bitacoraLab = bitacoraLab;
       this.lote = lote;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estatus = estatus;
       this.mantenimientos = mantenimientos;
       this.lotes = lotes;
       this.muestras = muestras;
       this.nombreLote=nombreLote;
    }
    
    
    

    public String getNombreLote() {
        return nombreLote;
    }

    public void setNombreLote(String nombreLote) {
        this.nombreLote = nombreLote;
    }
   
    
    
    public int getIdLote() {
        return this.idLote;
    }
    
    public void setIdLote(int idLote) {
        this.idLote = idLote;
    }
    public BitacoraLab getBitacoraLab() {
        return this.bitacoraLab;
    }
    
    public void setBitacoraLab(BitacoraLab bitacoraLab) {
        this.bitacoraLab = bitacoraLab;
    }
    public Lote getLote() {
        return this.lote;
    }
    
    public void setLote(Lote lote) {
        this.lote = lote;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Integer getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }
    public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }
    public Set getMuestras() {
        return this.muestras;
    }
    
    public void setMuestras(Set muestras) {
        this.muestras = muestras;
    }




}


