package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoMuestra generated by hbm2java
 */
public class TipoMuestra  implements java.io.Serializable {


     private int idTipoMues;
     private String nomMuestra;
     private Set muestras = new HashSet(0);

    public TipoMuestra() {
    }

	
    public TipoMuestra(int idTipoMues, String nomMuestra) {
        this.idTipoMues = idTipoMues;
        this.nomMuestra = nomMuestra;
    }
    public TipoMuestra(int idTipoMues, String nomMuestra, Set muestras) {
       this.idTipoMues = idTipoMues;
       this.nomMuestra = nomMuestra;
       this.muestras = muestras;
    }
   
    public int getIdTipoMues() {
        return this.idTipoMues;
    }
    
    public void setIdTipoMues(int idTipoMues) {
        this.idTipoMues = idTipoMues;
    }
    public String getNomMuestra() {
        return this.nomMuestra;
    }
    
    public void setNomMuestra(String nomMuestra) {
        this.nomMuestra = nomMuestra;
    }
    public Set getMuestras() {
        return this.muestras;
    }
    
    public void setMuestras(Set muestras) {
        this.muestras = muestras;
    }




}


