package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vector generated by hbm2java
 */
public class Vector  implements java.io.Serializable {


     private int codVector;
     private String nomVector;
     private String descVector;
     private Set invVectors = new HashSet(0);

    public Vector() {
    }

	
    public Vector(int codVector, String nomVector) {
        this.codVector = codVector;
        this.nomVector = nomVector;
    }
    public Vector(int codVector, String nomVector, String descVector, Set invVectors) {
       this.codVector = codVector;
       this.nomVector = nomVector;
       this.descVector = descVector;
       this.invVectors = invVectors;
    }
   
    public int getCodVector() {
        return this.codVector;
    }
    
    public void setCodVector(int codVector) {
        this.codVector = codVector;
    }
    public String getNomVector() {
        return this.nomVector;
    }
    
    public void setNomVector(String nomVector) {
        this.nomVector = nomVector;
    }
    public String getDescVector() {
        return this.descVector;
    }
    
    public void setDescVector(String descVector) {
        this.descVector = descVector;
    }
    public Set getInvVectors() {
        return this.invVectors;
    }
    
    public void setInvVectors(Set invVectors) {
        this.invVectors = invVectors;
    }




}


